---

  - file: path=/tmp/mysql state=directory

  - name: copy mysql docker file
    template: src=mysql-Dockerfile.j2 dest=/tmp/mysql/Dockerfile

  - name: build mysql
    docker_image: path="/tmp/mysql"
                  name="database/mysql"
                  state=present
                  tag={{mysql_version}}
    register: build_mysql
