---

  - include: postgresql-setup-schema.yml
    when: db_dialect == 'postgresql'

  - include: mysql-setup-schema.yml
    when: db_dialect == 'mysql'

#  - include: derby-setup-schema.yml
#    when: db_dialect == 'derby'
